application: openmobiledata
version: quic
runtime: python
api_version: 1
default_expiration: "600s"

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /visualization
  script: gspeedometer/main.py
  login: optional
  
- url: /its
  script: gspeedometer/main.py
  login: required

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /admin/.*
  script: gspeedometer/main.py
  login: admin

- url: /validation/data
  script: gspeedometer/main.py
  login: admin

- url: /anonymous/.*
  script: gspeedometer/main.py

- url: /.*
  script: gspeedometer/main.py
  login: required
